namespace D2NG.Core.D2GS.Packet
{
    public interface IncomingPacket
    {
        public byte GameLoading { get; }
        public byte GameFlags { get; }
        public byte LoadSuccessful { get; }
        public byte LoadAct { get; }
        public byte LoadActComplete { get; }
        public byte UnloadActComplete { get; }
        public byte GameExitSuccess { get; }
        public byte MapReveal { get; }
        public byte MapHide { get; }
        public byte AssignLevelWarp { get; }
        public byte RemoveObject { get; }
        public byte GameHandshake { get; }
        public byte NPCHit { get; }
        public byte PlayerStop { get; }
        public byte ObjectState { get; }
        public byte EntityMove { get; }
        public byte PlayerToTarget { get; }
        public byte ReportKill { get; }
        public byte UpdateEntityEffects { get; }
        public byte AddEntityEffect { get; }
        public byte AddEntityEffect2 { get; }
        public byte ReassignPlayer { get; }
        public byte LifeManaUpdatePot { get; }
        public byte GoldToInventory { get; }
        public byte AddExperienceByte { get; }
        public byte AddExperienceWord { get; }
        public byte AddExperienceDword { get; }
        public byte AddAttributeByte { get; }
        public byte AddAttributeWord { get; }
        public byte AddAttributeDword { get; }
        public byte AttributeUpdate { get; }
        public byte UpdateItemOSkill { get; }
        public byte UpdateItemSkill { get; }
        public byte SetSkill { get; }
        public byte Recv24 { get; }
        public byte Recv25 { get; }
        public byte ReceiveChat { get; }
        public byte NPCInfo { get; }
        public byte QuestInfo { get; }
        public byte GameQuestInfo { get; }
        public byte NPCTransaction { get; }
        public byte PlaySound { get; }
        public byte Recv2F { get; }
        public byte UpdateItemStats { get; }
        public byte UseStackableItem { get; }
        public byte Recv40 { get; }
        public byte ClearCursor { get; }
        public byte Recv45 { get; }
        public byte Relator1 { get; }
        public byte Relator2 { get; }
        public byte UseSkillOnTarget { get; }
        public byte UseSkillOnPoint { get; }
        public byte MercForHire { get; }
        public byte StartMercList { get; }
        public byte Recv50 { get; }
        public byte AssignObject { get; }
        public byte QuestLogInfo { get; }
        public byte PlayerSlotRefresh { get; }
        public byte Recv54 { get; }
        public byte AssignNPC1 { get; }
        public byte AssignNPC2 { get; }
        public byte Recv58 { get; }
        public byte AssignPlayer { get; }
        public byte EventMessage { get; }
        public byte PlayerInGame { get; }
        public byte PlayerLeftGame { get; }
        public byte QuestItemState { get; }
        public byte Recv5E { get; }
        public byte Recv5F { get; }
        public byte TownPortalState { get; }
        public byte Recv61 { get; }
        public byte Recv62 { get; }
        public byte WaypointMenu { get; }
        public byte PlayerKillCount { get; }
        public byte Recv66 { get; }
        public byte NPCMove { get; }
        public byte NPCMoveToTarget { get; }
        public byte NPCState { get; }
        public byte Recv6A { get; }
        public byte NPCAction { get; }
        public byte NPCAttack { get; }
        public byte NPCStop { get; }
        public byte Recv6E { get; }
        public byte Recv6F { get; }
        public byte Recv70 { get; }
        public byte Recv71 { get; }
        public byte Recv72 { get; }
        public byte Recv73 { get; }
        public byte PlayerCorpseAssign { get; }
        public byte PlayerPartyInfo { get; }
        public byte PlayerInProximity { get; }
        public byte ButtonAction { get; }
        public byte TradeAccepted { get; }
        public byte GoldInTrade { get; }
        public byte PetAction { get; }
        public byte AssignHotkey { get; }
        public byte UseScroll { get; }
        public byte SetItemState { get; }
        public byte Recv7E { get; }
        public byte AllyPartyInfo { get; }
        public byte AssignMerc { get; }
        public byte PortalOwner { get; }
        public byte Recv86 { get; }
        public byte SpecialQuestEvent { get; }
        public byte NPCWantInteract { get; }
        public byte PlayerRelationship { get; }
        public byte RelationshipUpdate { get; }
        public byte AssignPlayerToParty { get; }
        public byte CorpseAssign { get; }
        public byte Pong { get; }
        public byte PartyAutomapInfo { get; }
        public byte Recv91 { get; }
        public byte Recv92 { get; }
        public byte Recv93 { get; }
        public byte BaseSkillLevels { get; }
        public byte LifeManaUpdate { get; }
        public byte WalkVerify { get; }
        public byte WeaponSwitch { get; }
        public byte Recv98 { get; }
        public byte SkillTriggered { get; }
        public byte Recv9A { get; }
        public byte Recv9B { get; }
        public byte WorldItemAction { get; }
        public byte OwnedItemAction { get; }
        public byte MercAttributeByte { get; }
        public byte MercAttributeWord { get; }
        public byte MercAttributeDword { get; }
        public byte AddMercExperienceByte { get; }
        public byte AddMercExperienceWord { get; }
        public byte Recva3 { get; }
        public byte Recva4 { get; }
        public byte ChargeupActive { get; }
        public byte DelayedState { get; }
        public byte LeaveGameConfirmed { get; }
        public byte EndState { get; }
        public byte AddUnit { get; }
        public byte NPCHeal { get; }
        public byte Recvad { get; }
        public byte WardenRequest { get; }
        public byte GameDropped { get; }
        public byte Recvb1 { get; }
        public byte IPBan { get; }
    }
}