namespace D2NG
{
    public enum Attribute
    {
        Strength = 0x00,
        Energy = 0x01,
        Dexterity = 0x02,
        Vitality = 0x03,
        StatRemaining = 0x04,
        SkillRemaining = 0x05,
        Level = 0x0C,
        Experience = 0x0D,
        GoldOnPerson = 0x0E,
        GoldInStash = 0x0F,
        Defense = 0x10,
        MaxAttackDamage = 0x11,
        MinAttackDamage = 0x12,
        AttackRating = 0x13,
        MinAttackDamage2 = 0x15,
        MaxAttackDamage2 = 0x16,
        Damage = 0x19,
        Defense2 = 0x1f,
        FireResistance = 0x27,
        MaxFireResistance = 0x28,
        ColdResistance = 0x29,
        MaxColdResistance = 0x2A,
        LightningResistance = 0x2B,
        MaxLightningResistance = 0x2C,
        PoisonResistance = 0x2D,
        MaxPoisonResistance = 0x2E,
        AddFireDamage = 0x31,
        AddLightningDamage = 0x33,
        AddColdDamage = 0x35,
        AddDamage = 0x37,
        AddPoisonDamage = 0x3A,
        AddMaxHealth = 0x4C,
        AddMaxMana = 0x4D,
        AddMaxStamina = 0xA2,
        AddMaxStamina2 = 0xA3,
        AddToDefense = 0xAB,
    }
}